local g = vim.g

g.user_emmet_mode = 'inv'
g.user_emmet_expandabbr_key = '<C-y>,'
g.user_emmet_expandword_key = '<C-y>;'
g.user_emmet_update_tag = '<C-y>u'
g.user_emmet_balancetaginward_key = '<C-y>d'
g.user_emmet_balancetagoutward_key = '<C-y>D'
g.user_emmet_next_key = '<C-y>n'
g.user_emmet_prev_key = '<C-y>N'
g.user_emmet_imagesize_key = '<C-y>i'
g.user_emmet_togglecomment_key = '<C-y>/'
g.user_emmet_splitjointag_key = '<C-y>j'
g.user_emmet_removetag_key = '<C-y>k'
g.user_emmet_anchorizeurl_key = '<C-y>a'
g.user_emmet_anchorizesummary_key = '<C-y>A'
g.user_emmet_mergelines_key = '<C-y>m'
g.user_emmet_codepretty_key = '<C-y>c'
