if OS.mac?
  tap "homebrew/cask"
  tap "homebrew/cask-fonts"

  brew "git"
  brew "reattach-to-user-namespace"

  cask "font-3270-nerd-font"
  cask "font-anonymouspro-nerd-font-mono"
  cask "font-cascadia-mono"
  cask "font-fira-code"
  cask "font-firacode-nerd-font"
  cask "font-source-code-pro"
  cask "font-victor-mono"
end

tap "homebrew/bundle"
tap "homebrew/core"

brew "ack"
brew "bat"
brew "cabextract"
brew "cmake"
brew "diff-so-fancy"
brew "fish"
brew "fzf"
brew "gcc"
brew "gnupg"
brew "grep"
brew "highlight"
brew "htop"
brew "hub"
brew "lazydocker"
brew "lazygit"
brew "make"
brew "neofetch"
brew "neovim"
brew "python"
brew "ripgrep"
brew "shellcheck"
brew "stow"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "vim"
brew "xclip"
brew "z"
brew "zsh"
