if OS.mac?
  tap "homebrew/cask"
  tap "homebrew/cask-fonts"

  brew "mas"
  brew "noti"
  brew "highlight"

  cask "font-3270-nerd-font"
  cask "font-cascadia-mono"
  cask "font-fira-code"
  cask "font-fira-code-nerd-font"
  cask "font-jetbrains-mono"
  cask "font-source-code-pro"
  cask "font-victor-mono"

  cask "amethyst"
  cask "kitty"
  cask "notion"
  cask "postman"
  cask "firefox"
  cask "google-chrome"
end

tap "homebrew/bundle"
tap "homebrew/core"

brew "ack"
brew "bat"
brew "cloc"
brew "cmake"
brew "diff-so-fancy"
brew "efm-langserver"
brew "fd"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "gnupg"
brew "go"
brew "grep"
brew "htop"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "luarocks"
brew "make"
brew "markdown"
brew "neofetch"
brew "neovim"
brew "ninja"
brew "python"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "stow"
brew "tmux"
brew "tree"
brew "vim"
brew "wget"
brew "z"
brew "zsh"
