require('plugins')
require('settings')
require('keymaps')

-- plugins
require('plg-compe')
require('plg-floatterm')
require('plg-autopairs')
require('plg-nvimtree')
require('plg-barber')
require('plg-treesitter')
require('plg-galaxyline')
require('plg-emmet')
require('plg-comment')
require('plg-gitsigns')
require('plg-colorizer')
require('plg-telescope')
require('plg-lspkind')

-- LSP
require('lsp')
require('lsp.bash-ls')
require('lsp.css-ls')
require('lsp.docker-ls')
require('lsp.html-ls')
require('lsp.json-ls')
require('lsp.lua-ls')
require('lsp.saga-ls')
require('lsp.tsserver-ls')
require('lsp.vim-ls')
require('lsp.yaml-ls')
require('lsp.efm-ls')
