-- Reusable config/settings for my Neovim config
DATA_PATH = vim.fn.stdpath 'data'
NVIM_PATH = os.getenv 'HOME' .. '/.config/nvim'
SUMNEKO_PATH = os.getenv 'HOME' .. '/lua-language-server'

Lvim = {
  leader = ',',
  colorscheme = 'onedarker',
  packerInstallPath = DATA_PATH .. '/site/pack/packer/start/packer.nvim',
  vsnip_dir = NVIM_PATH .. '/snippets',

  icons = {
    bomb = '  ',
    scissors = '  ',
    warningCircle = '  ',
    warningTriangle = '  ',
    warningTriangleNoBg = '  ',
    info = '  ',
    infoNoBg = '  ',
    error = '  ',
    errorSlash = ' ﰸ ',
    fileNoBg = '  ',
    fileCutCorner = '  ',
    fileBg = '  ',
    fileNoLines = '  ',
    fileNoLinesBg = '  ',
    folder = '  ',
    folderOpen = '  ',
    folderNoBg = '  ',
    folderOpenNoBg = '  ',
    scope = '  ',
    pie = '  ',
    ribbon = '  ',
    ribbonNoBg = '  ',
    database = ' ﬘ ',
    box = '  ',
    key = '  ',
    toggleSelected = ' 蘒',
    curlies = '  ',
    lightbulb = '  ',
    m = ' m ',
    f = '  ',
    settings = '  ',
    gears = '  ',
    container = '  ',
    threeDots = '  ',
    threeDotsBoxed = '  ',
    calculator = '  ',
    hexCutOut = '  ',
    vim = '  ',
    pencil = '  ',
    tree = '  ',
    treeDiagram = '  ',
    happyFace = ' ﲃ ',
    emptyBox = '  ',
    fileCopy = '  ',
    timer = '  ',
    t = '  ',
    abc = '  ',
    numbers = '  ',
    wrench = '  ',
    ruler = ' 塞',
    rectangleIntersect = ' 練',
    paragraph = '  ',
    paint = '  ',
    sort = '  ',
    cubeTree = '  ',
    search = '  ',
    arrowReturn = '  ',
    git = '  ',
    gitAdd = '  ',
    gitChange = ' 柳',
    gitRemove = '  ',
  },

  colors = {
    bg = '#2E2E2E',
    yellow = '#DCDCAA',
    dark_yellow = '#D7BA7D',
    cyan = '#4EC9B0',
    green = '#608B4E',
    light_green = '#B5CEA8',
    string_orange = '#CE9178',
    orange = '#FF8800',
    purple = '#C586C0',
    magenta = '#D16D9E',
    grey = '#858585',
    blue = '#569CD6',
    vivid_blue = '#4FC1FF',
    light_blue = '#9CDCFE',
    red = '#D16969',
    error_red = '#F44747',
    info_yellow = '#FFCC66'
  },
}

return Lvim
