##############################
###### Plugin Settings #######
##############################

# FZF Switcher Config
set -g @fzf_pane_switch_bind-key "w"
# default format session_name window_name pane_title pane_current_command
set -g @fzf_pane_switch_list-panes-format "session_name"
set -g @fzf_pane_switch_window-position "center,90%"
set -g @fzf_pane_switch_preview-pane-position "right,,,nowrap"

tm_tunes="#(osascript -l JavaScript $DOTFILES/applescripts/tunes.js)"

# Tokyo Night Theme configuration
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_transparent_status_bar 'true'
set -g @theme_transparent_left_separator_inverse ''
set -g @theme_transparent_right_separator_inverse ''
set -g @powerkit_plugin_datetime_format "%m-%d-%Y %I:%M %p"
set -g @powerkit_plugin_weather_location "Honey Brook"
set -g @powerkit_plugin_weather_format "%t H:%h %C"
set -g @powerkit_plugin_weather_units "u"
set -g @powerkit_plugins "datetime,weather,$tm_tunes"
set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"

######################
###### Plugins #######
######################
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tmux-powerkit'
set -g @plugin 'kristijan/tmux-fzf-pane-switch'

run '~/.tmux/plugins/tpm/tpm'

######################
###### Settings ######
######################

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set-option -g status-position top

set -g base-index 1
set -g pane-base-index 1

# enable mouse support for switching panes/windows
setw -g mouse on

######################
#### Key Bindings ####
######################

# set tmux prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# reload config file
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# quickly switch to another tmux session
bind-key -r f run-shell "tmux neww ~/.dotfiles/bin/tmux-sessionizer"

# toggle split layouts
bind -n M-a select-layout main-vertical
bind -n M-A select-layout main-horizontal
bind -n M-E select-layout even-vertical
bind -n M-V select-layout even-horizontal

# split window and fix path for tmux 1.9
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# show and hide panes
bind ! break-pane -d
bind @ join-pane -s !

# resize pane shortcuts
bind -r H resize-pane -L 10
bind -r J resize-pane -D 10
bind -r K resize-pane -U 10
bind -r L resize-pane -R 10

# set vi mode for copy mode
setw -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
