name: CI for Mac

on:
  pull_request:
    branches: ["main"]

jobs:
  build_and_test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Setting up the environment
        shell: bash
        run: |
          ./install.sh
        env:
          REPO: ${{github.workspace}}
          DOTFILES_REF: ${{github.sha}}
          HOMEBREW_BUNDLE_BREW_SKIP: "node"
          OPERATING_SYSTEM: "mac"
          USE_BREW: "true"
