name: Test Dotfiles

on:
  pull_request:
    branches: ["main"]

jobs:
  build_and_test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Setting up the environment
        shell: bash
        run: |
          ./install.sh
        env:
          REPO: ${{github.workspace}}
          DOTFILES_REF: ${{github.sha}}
          HOMEBREW_BUNDLE_BREW_SKIP: "node"
          OPERATING_SYSTEM: "mac"
          USE_BREW: "true"
  build_and_test_arch:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: archlinux/archlinux:base-devel
          command: bash
          workdir: /root
          options: -v ${{ github.workspace }}:/root -e OPERATING_SYSTEM=arch -e USE_BREW=true -e DOTFILES_REF=${{ github.sha }} -e REPO=${{ github.workspace }}
          run: |
            pacman-key --init
            pacman-key --populate
            pacman -Syu --noconfirm
            pacman -S --noconfirm --needed git curl wget
            ./install.sh
