name: 'Testing dotfiles'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu_20_04:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Testing Ubuntu 20.04'
        uses: ./
